/* Plain names for the tasks, as the site presents them. The corpus is frozen and keeps its own names (the
   question-style ones); this only changes presentation. Per task: the job in a few words, one sentence on what
   the model reads and decides, and what it chooses between. */
export const TASK_COPY = {
  'ENG-1': ['Find the file to fix', 'Read a GitHub issue and pick the file that the real fix changed.', 'One of five files from the repository'],
  'ENG-2': ['Label a code change', 'Read a diff and say whether it is a fix, a feature, docs, a refactor or a test.', 'One of five commit types'],
  'ENG-3': ['Classify a vulnerability', 'Read a CVE description and name its weakness class, such as injection or path traversal.', 'One of six weakness classes'],
  'ENG-4': ['Triage a secret-scanner alert', 'Decide whether a flagged value is a real credential, a placeholder or no secret at all.', 'Real, placeholder or not a secret'],
  'ENG-5': ['Match a diff to its commit', 'Pick which of four commit messages was written for this diff.', 'One of four messages from the same repository'],
  'AGT-1': ['Pick the right tool', 'Given a user request and the functions on offer, choose the one to call, or none.', 'One of the offered functions, or none'],
  'AGT-2': ['Spot a hijacked agent', 'Read an agent run that met a prompt injection and say whether the agent obeyed it.', 'Hijacked or not'],
  'AGT-3': ['Check the agent finished the job', 'Read a support agent’s conversation and decide whether the customer got what they needed.', 'Completed or not'],
  'AGT-4': ['Check an answer against its sources', 'Decide whether a cited answer is backed by the passages it cites.', 'Supported or not'],
  'AGT-5': ['Pick the better reply', 'Compare two assistant replies to the same question and choose the better one.', 'Reply A or reply B'],
  'SAF-1': ['Catch prompt attacks', 'Decide whether a chat message is ordinary, a prompt injection or a jailbreak.', 'Benign, injection or jailbreak'],
  'SAF-2': ['Flag toxic comments', 'Decide whether a reader’s comment on a news article is toxic.', 'Toxic or not'],
  'SUP-1': ['Route a complaint', 'Send a consumer complaint to the product team that owns it.', 'One of seven product teams'],
  'SUP-2': ['Tag what a complaint is about', 'Name the issue a consumer complaint raises, such as a debt not owed or a purchase dispute.', 'One of eight issues'],
  'COM-1': ['Grade search relevance', 'Judge how well a product fits a shopper’s search: exact, substitute, complement or irrelevant.', 'One of four relevance grades'],
  'COM-2': ['Categorise a product listing', 'Name the product type from a listing’s title and details.', 'One of eight product types'],
  'COM-3': ['Classify a company’s industry', 'Read a company’s 10-K business description and pick its SIC industry division.', 'One of seven SIC divisions'],
  'FIN-1': ['Place a 10-K passage', 'Say which section of an annual report a passage was taken from.', 'One of five sections'],
  'FIN-2': ['Classify an 8-K filing', 'Say what event a company’s current report discloses, such as results or an officer change.', 'One of five event types'],
  'FIN-3': ['Find the receipt total', 'Look at a photo of a receipt and pick the total amount charged.', 'One of the amounts printed on the receipt'],
  'FIN-4': ['Tag a reported figure', 'Say what a marked dollar amount in a filing reports, such as revenue or goodwill.', 'One of six financial concepts'],
  'LEG-1': ['Check a claim against an NDA', 'Decide whether the agreement states something, states the opposite or does not cover it.', 'Yes, the opposite, or not addressed'],
  'LEG-2': ['Classify a contract clause', 'Name a clause’s type, such as governing law or a cap on liability.', 'One of six clause types'],
  'LEG-3': ['Flag unfair terms of service', 'Decide whether a terms-of-service sentence is unfair to consumers, and in what way.', 'Not unfair, or one of eight unfair types'],
  'LEG-4': ['Find a clause in a contract', 'Decide whether a contract excerpt contains a given type of clause.', 'Yes or no'],
  'PRD-1': ['Predict the winning headline', 'Two headlines were tested on real readers. Pick the one that got more clicks.', 'Headline A or headline B'],
  'PRD-2': ['Call the version bump', 'Read a release’s notes and decide whether it is a major, minor or patch release.', 'Major, minor or patch'],
  'DAT-1': ['Pick the right SQL query', 'Given a database schema and a question, choose the query that answers it.', 'One of four SQL queries'],
  'DAT-2': ['Answer from a table', 'Pick the cell that answers a question about a table.', 'One of four values from the table'],
  'DAT-3': ['Fact-check a chart', 'Decide whether a line chart’s data supports a claim made about it.', 'Supported or not'],
  'DAT-4': ['Guess what a column holds', 'From fifteen values of an unnamed CSV column, say what kind of data it holds.', 'One of seven kinds of value'],
  'DOC-1': ['Identify the document type', 'From a single page, say whether it comes from a patent, a manual, a financial report and so on.', 'One of six document types'],
  'DOC-2': ['Spot decisions and action items', 'Decide whether a highlighted line in a meeting is a decision, an action item or neither.', 'Decision, action item or neither'],
  'DOC-3': ['Match a meeting to its summary', 'Pick which of four summaries describes this meeting.', 'One of four summaries'],
  'DSN-1': ['Name an icon', 'Look at a Material Symbols icon and pick its official name.', 'One of four icon names from the same category'],
};
