#!/usr/bin/env python3
"""Build and freeze Decision Bench v4 (data/corpus/bench-v4).

  --dry-run          build and check; write nothing under data/corpus
  --dump PREFIX      with --dry-run, print rows whose id starts with PREFIX (e.g. pi-1)
  --summary          with --dry-run, print one line per row: id | answer | title
  --only MOD[,MOD]   build only these category modules (dry-run only; the frozen corpus needs every module)
"""
import argparse
import collections
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from authoring import bench
from decision_bench.corpus import canonical, digest, validate


def sources_markdown(rows):
    """data/SOURCES.md, generated from each module's DATASETS so the attribution can't drift from the rows."""
    real = [r for r in rows if r["source_kind"] == "real"]
    count = collections.Counter(r["source"]["dataset_id"] for r in real)
    per_task = collections.defaultdict(collections.Counter)
    for r in real:
        per_task[r["source"]["dataset_id"]][r["task"]] += 1
    out = ["# Data sources and attribution", "",
           "<!-- Generated by scripts/build_bench.py from the DATASETS declared in authoring/bench/*.py. "
           "Edit those, not this file. -->", "",
           f"Decision Bench {bench.SUITE} has {len(rows)} rows, every one a real record sampled from the public "
           "datasets below. Nothing in the corpus was written or generated for the benchmark.", "",
           "**Licence policy.** A dataset is used only if its own licence *and* the terms of the text or images inside it "
           "allow anyone to copy, modify and redistribute it, including commercially (MIT, Apache-2.0, BSD, CC0, "
           "CC BY, CC BY-SA, public domain). Datasets built on non-commercial or publisher-copyrighted text are "
           "not used, even when the dataset itself is MIT. Each row keeps its source license; CC BY-SA rows stay "
           "CC BY-SA.", "",
           "Every real row names its dataset, license, URL, record id and original label in its `source` field. "
           "`data/sources/manifest.json` pins the sha256 of every upstream file; `python3 scripts/fetch_sources.py` "
           "re-downloads and verifies them. The raw downloads are not committed.", "",
           "If you are a rights holder and want a row removed, open an issue using the *Data removal request* "
           "template, or see [SECURITY.md](../SECURITY.md) to report it privately.", "",
           "| Dataset | Tasks | Rows | License | Text inside | Answers from |", "| --- | --- | --- | --- | --- | --- |"]
    for d in bench.DATASETS.values():
        tasks = ", ".join(f"{t} ({n})" for t, n in sorted(per_task[d["id"]].items()))
        inner = d["content_license"] if d["content_license"] != d["license"] else "same"
        out.append(f"| [{d['name']}](#{d['id']}) | {tasks} | {count[d['id']]} | [{d['license']}]({d['license_url']}) "
                   f"| {inner} | {d['labelled_by']} |")
    for d in bench.DATASETS.values():
        out += ["", f'<a id="{d["id"]}"></a>', f"## {d['name']}", "",
                f"- **Homepage:** {d['homepage']}",
                f"- **License:** [{d['license']}]({d['license_url']})",
                f"- **What a row contains:** {d['content']}",
                f"- **Terms of that text:** {d['content_license']}. {d['content_terms']}",
                f"- **Answers from:** {d['labelled_by']}",
                f"- **How rows were chosen:** {d['selection']}",
                f"- **What we changed:** {d['changes']}",
                f"- **Cite:** {d['citation']}", "", "```bibtex", d["bibtex"].strip(), "```"]
    return "\n".join(out) + "\n"


def tasks_markdown(rows):
    """docs/tasks.md, generated from the registered tasks so the public task list never drifts from the corpus."""
    by_task = collections.defaultdict(list)
    for r in rows:
        by_task[r["task"]].append(r)
    real = sum(r["source_kind"] == "real" for r in rows)
    out = ["# Tasks", "",
           "<!-- Generated by scripts/build_bench.py from the tasks registered in authoring/bench/*.py. "
           "Edit those, not this file. -->", "",
           f"Decision Bench {bench.VERSION} has **{len(rows)} rows in {len(bench.TASKS)} tasks and "
           f"{len({r['category'] for r in rows})} use-case categories**. Every row is a real record from a public "
           f"dataset ({real} of {len(rows)}); the answer is the dataset's own label or an objective record, never a "
           "model's output. Sources, licences and citations are in [data/SOURCES.md](../data/SOURCES.md); how rows "
           "are chosen is in [authoring-v4.md](authoring-v4.md).", ""]
    for cat, (name, desc) in bench.CATEGORIES.items():
        tasks = [t for t in bench.TASKS if bench.TASKS[t]["category"] == cat and by_task.get(t)]
        if not tasks:
            continue
        out += [f"## {name}", "", desc, "",
                "| Task | Question | Options | Rows | Input | Answer from | Source |", "| --- | --- | --- | --- | --- | --- | --- |"]
        for t in tasks:
            info, items = bench.TASKS[t], by_task[t]
            opts = "from the record" if info["per_row_options"] else " · ".join(k.replace("_", " ") for k in info["options"])
            datasets = ", ".join(sorted({bench.DATASETS[r["source"]["dataset_id"]]["name"] for r in items}))
            inp = f"{info['input_type']}" + (" (image)" if info["modality"] != "text" else "")
            out.append(f"| {t} {info['name']} | {info['ask']} | {opts} | {len(items)} | {inp} | {info['label_origin']} | {datasets} |")
        out.append("")
    out += ["## Labels on every task", "",
            "- **Decision shape:** " + "; ".join(f"*{k}*: {v}" for k, v in bench.SHAPES.items()),
            "- **Expertise needed:** " + "; ".join(f"*{k}*: {v}" for k, v in bench.EXPERTISE.items()),
            "- **Contamination risk:** low (a fresh derivation), medium (a public dataset that may be in training data), "
            "high (a well-known benchmark).",
            "- **Answer from:** who or what decided the key: " + ", ".join(sorted(bench.LABEL_ORIGINS)) + ".",
            "- **Difficulty** is never authored; the site shows how many models got each row right.", ""]
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--dump")
    parser.add_argument("--summary", action="store_true")
    parser.add_argument("--only")
    args = parser.parse_args()
    if args.only and not args.dry_run:
        raise SystemExit("--only is for --dry-run; the frozen corpus is built from every module")
    rows = bench.build(args.only.split(",") if args.only else None)
    counts = validate(rows)
    problems = bench.check(rows)
    report = {"counts": counts,
              "tasks": {t: {"rows": sum(r["task"] == t for r in rows),
                            "answers": dict(collections.Counter(r["questions"][0]["gold"] for r in rows
                                                                if r["task"] == t))}
                        for t in bench.TASKS},
              "real_rows": sum(r["source_kind"] == "real" for r in rows),
              "problems": problems}
    if args.dry_run:
        for r in rows:
            if args.dump is not None and r["id"].startswith(args.dump):
                print(json.dumps(r, ensure_ascii=False, indent=2))
            if args.summary:
                print(f"{r['id']:<40} {r['questions'][0]['gold']:<24} {r['title']}")
        print(json.dumps(report, indent=2), file=sys.stderr)
        return
    if problems:
        raise SystemExit("Checks failed:\n" + "\n".join(problems))
    folder = ROOT / "data/corpus" / bench.SUITE
    folder.mkdir(parents=True, exist_ok=True)
    target, manifest_path = folder / "cases.jsonl", folder / "manifest.json"
    content = "".join(canonical(r) + "\n" for r in rows)
    if target.exists() and target.read_text() != content and manifest_path.exists():
        sha = json.loads(manifest_path.read_text())["sha256"]
        if any(json.loads(p.read_text())["config"]["corpus_sha256"] == sha for p in (ROOT / "runs").glob("*/run.json")):
            raise SystemExit(f"{bench.SUITE} has inference runs; create a new version instead of overwriting it.")
    manifest = {"version": bench.VERSION, "suite": bench.SUITE, "label": "Decision Bench", "sha256": digest(rows),
                "license": "Code: MIT. Every row keeps its source licence (see each row and data/SOURCES.md).",
                "categories": {k: {"name": v[0], "description": v[1]} for k, v in bench.CATEGORIES.items()},
                "tasks": {k: bench.task_summary(k, rows) for k in bench.TASKS},
                "shapes": bench.SHAPES, "expertise": bench.EXPERTISE,
                "counts": counts, "real_rows": report["real_rows"], "frozen_before_inference": True,
                "sampling": "Deterministic: records ordered by sha256 of their source id and filtered by written "
                            "rules; no model output used.",
                "contamination": "Public datasets may appear in model training data; scores may be inflated."}
    manifest["datasets"] = {d["id"]: {k: d[k] for k in ("name", "license", "content_license", "homepage")}
                            for d in bench.DATASETS.values()}
    target.write_text(content)
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    (ROOT / "data/datasets.json").write_text(json.dumps(
        {"suite": bench.SUITE, "datasets": list(bench.DATASETS.values())}, indent=2, ensure_ascii=False) + "\n")
    (ROOT / "data/SOURCES.md").write_text(sources_markdown(rows))
    (ROOT / "docs/tasks.md").write_text(tasks_markdown(rows))
    (ROOT / "data/corpus/current.json").write_text(json.dumps(
        {"path": str(target.relative_to(ROOT)), "version": manifest["version"]}, indent=2) + "\n")
    print(json.dumps({k: manifest[k] for k in ("version", "sha256", "counts", "real_rows")}, indent=2))


if __name__ == "__main__":
    main()
