#!/usr/bin/env python3
"""Build and freeze Decision Bench v3 (data/corpus/bench-v3).

  --dry-run          build and check; write nothing under data/corpus
  --dump PREFIX      with --dry-run, print rows whose id starts with PREFIX (e.g. pi-1)
  --summary          with --dry-run, print one line per row: id | answer | title
"""
import argparse
import collections
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from authoring import bench
from decision_bench.corpus import canonical, digest, validate


def sources_markdown(rows):
    """data/SOURCES.md, generated from each module's DATASETS so the attribution can't drift from the rows."""
    real = [r for r in rows if r["source_kind"] == "real"]
    count = collections.Counter(r["source"]["dataset_id"] for r in real)
    per_task = collections.defaultdict(collections.Counter)
    for r in real:
        per_task[r["source"]["dataset_id"]][r["task"]] += 1
    out = ["# Data sources and attribution", "",
           "<!-- Generated by scripts/build_bench.py from the DATASETS declared in authoring/bench/*.py. "
           "Edit those, not this file. -->", "",
           f"Decision Bench {bench.SUITE} has {len(rows)} rows. {len(real)} are real records sampled from the public "
           f"datasets below; the other {len(rows) - len(real)} are written examples (skill improvement), MIT "
           "licensed with the code.", "",
           "**License policy.** A dataset is used only if its own license *and* the terms of the text inside it "
           "allow anyone to copy, modify and redistribute it, including commercially (MIT, Apache-2.0, BSD, CC0, "
           "CC BY, CC BY-SA, public domain). Datasets built on non-commercial or publisher-copyrighted text are "
           "not used, even when the dataset itself is MIT. Each row keeps its source license; CC BY-SA rows stay "
           "CC BY-SA.", "",
           "Every real row names its dataset, license, URL, record id and original label in its `source` field. "
           "`data/sources/manifest.json` pins the sha256 of every upstream file; `python3 scripts/fetch_sources.py` "
           "re-downloads and verifies them. The raw downloads are not committed.", "",
           "If you are a rights holder and want a row removed, open an issue using the *Data removal request* "
           "template, or see [SECURITY.md](../SECURITY.md) to report it privately.", "",
           "| Dataset | Tasks | Rows | License | Text inside | Answers from |", "| --- | --- | --- | --- | --- | --- |"]
    for d in bench.DATASETS.values():
        tasks = ", ".join(f"{t} ({n})" for t, n in sorted(per_task[d["id"]].items()))
        inner = d["content_license"] if d["content_license"] != d["license"] else "same"
        out.append(f"| [{d['name']}](#{d['id']}) | {tasks} | {count[d['id']]} | [{d['license']}]({d['license_url']}) "
                   f"| {inner} | {d['labelled_by']} |")
    for d in bench.DATASETS.values():
        out += ["", f'<a id="{d["id"]}"></a>', f"## {d['name']}", "",
                f"- **Homepage:** {d['homepage']}",
                f"- **License:** [{d['license']}]({d['license_url']})",
                f"- **What a row contains:** {d['content']}",
                f"- **Terms of that text:** {d['content_license']}. {d['content_terms']}",
                f"- **Answers from:** {d['labelled_by']}",
                f"- **How rows were chosen:** {d['selection']}",
                f"- **What we changed:** {d['changes']}",
                f"- **Cite:** {d['citation']}", "", "```bibtex", d["bibtex"].strip(), "```"]
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--dump")
    parser.add_argument("--summary", action="store_true")
    args = parser.parse_args()
    rows = bench.build()
    counts = validate(rows)
    problems = bench.check(rows)
    report = {"counts": counts,
              "tasks": {t: {"rows": sum(r["task"] == t for r in rows),
                            "answers": dict(collections.Counter(r["questions"][0]["gold"] for r in rows
                                                                if r["task"] == t))}
                        for t in bench.TASKS},
              "real_rows": sum(r["source_kind"] == "real" for r in rows),
              "problems": problems}
    if args.dry_run:
        for r in rows:
            if args.dump is not None and r["id"].startswith(args.dump):
                print(json.dumps(r, ensure_ascii=False, indent=2))
            if args.summary:
                print(f"{r['id']:<40} {r['questions'][0]['gold']:<24} {r['title']}")
        print(json.dumps(report, indent=2), file=sys.stderr)
        return
    if problems:
        raise SystemExit("Checks failed:\n" + "\n".join(problems))
    folder = ROOT / "data/corpus" / bench.SUITE
    folder.mkdir(parents=True, exist_ok=True)
    target, manifest_path = folder / "cases.jsonl", folder / "manifest.json"
    content = "".join(canonical(r) + "\n" for r in rows)
    if target.exists() and target.read_text() != content and manifest_path.exists():
        sha = json.loads(manifest_path.read_text())["sha256"]
        if any(json.loads(p.read_text())["config"]["corpus_sha256"] == sha for p in (ROOT / "runs").glob("*/run.json")):
            raise SystemExit("bench-v3 has inference runs; create a new version instead of overwriting it.")
    manifest = {"version": "3.0.0", "suite": bench.SUITE, "label": "Decision Bench", "sha256": digest(rows),
                "license": "Code and written examples: MIT. Real rows keep their source license (see each row "
                           "and data/SOURCES.md).",
                "categories": {k: {"name": v[0], "description": v[1]} for k, v in bench.CATEGORIES.items()},
                "tasks": {k: {kk: v[kk] for kk in ("category", "name", "ask")} for k, v in bench.TASKS.items()},
                "counts": counts, "real_rows": report["real_rows"], "frozen_before_inference": True,
                "sampling": "Deterministic: records ordered by sha256 of their source id and filtered by written "
                            "rules; no model output used.",
                "contamination": "Public datasets may appear in model training data; scores may be inflated."}
    manifest["datasets"] = {d["id"]: {k: d[k] for k in ("name", "license", "content_license", "homepage")}
                            for d in bench.DATASETS.values()}
    target.write_text(content)
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    (ROOT / "data/datasets.json").write_text(json.dumps(
        {"suite": bench.SUITE, "datasets": list(bench.DATASETS.values())}, indent=2, ensure_ascii=False) + "\n")
    (ROOT / "data/SOURCES.md").write_text(sources_markdown(rows))
    (ROOT / "data/corpus/current.json").write_text(json.dumps(
        {"path": str(target.relative_to(ROOT)), "version": manifest["version"]}, indent=2) + "\n")
    print(json.dumps({k: manifest[k] for k in ("version", "sha256", "counts", "real_rows")}, indent=2))


if __name__ == "__main__":
    main()
